# Generated by Django 4.0.6 on 2022-07-25 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='previewText',
            field=models.CharField(default='none', max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.CharField(max_length=100),
        ),
    ]
