# Generated by Django 4.0.6 on 2022-07-26 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
